export const AUTH = '/'
export const HOME = '/home'
export const NEW_POST = '/posts/new'
export const NEW_COMMUNITY = '/communities/new'
export const ABOUT_COMMUNITY = '/communities/about'
export const PROFILE_SETTINGS = '/profile/settings'
export const SETTINGS_FEEDBACK = '/profile/settings/feedback'
export const PROFILE_EDIT = '/profile/settings/edit'
